# Generated by Django 5.1.3 on 2024-12-19 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_advertisement_dislike_advertisement_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='like',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='Dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
