# Generated by Django 5.1.3 on 2025-01-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='advertisement_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
